insert into clients ( client_name, client_add_date ) values ( 'users-subsystem', now() );
insert into clients ( client_name, client_add_date ) values ( 'ms-webapp', now() );

insert into organizations ( org_name, org_add_date ) values ( 'ClearPay Systems', now() );
insert into organizations ( org_name, org_add_date ) values ( 'Alliance of Cambridge Advisors', now() );
insert into organizations ( org_name, org_add_date ) values ( 'Alliance of Cambridge Brokers', now() );
insert into organizations ( org_name, org_add_date ) values ( 'Australian Council of Life Insurers', now() );
insert into organizations ( org_name, org_add_date ) values ( 'Australian Institute of Certified Public Accountants', now() );

insert into roles ( role_name, role_add_date ) values ( 'users subsystem admin', now() );
insert into roles ( role_name, role_add_date ) values ( 'manager', now() );
insert into roles ( role_name, role_add_date ) values ( 'broker', now() );

insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'USERS-SUBSYSTEM-ADMIN', 'ADMIN', 'ADMIN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MBAE', 'MARIAM', 'BAE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DSTROUTH', 'DUSTIN', 'STROUTH', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CSILVESTRI', 'CLOTILDE', 'SILVESTRI', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DGONSKA', 'DONNY', 'GONSKA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DSLOBODNIK', 'DONNA', 'SLOBODNIK', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'OASKREN', 'OLLIE', 'ASKREN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EURABE', 'EDMUND', 'URABE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CDELMONACO', 'CALVIN', 'DELMONACO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MESTREM', 'MICHEAL', 'ESTREM', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'GCHEA', 'GUILLERMO', 'CHEA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CGRAW', 'CECIL', 'GRAW', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SALBALADEJO', 'STEPHINE', 'ALBALADEJO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AWESNER', 'AMADA', 'WESNER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EBRITNELL', 'ELENORE', 'BRITNELL', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'BROGER', 'BENNIE', 'ROGER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'OHASKEW', 'ORVAL', 'HASKEW', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SDALTORIO', 'SHERMAN', 'DALTORIO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'JHUTCHINGSON', 'JAYE', 'HUTCHINGSON', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SPICHT', 'SOLOMON', 'PICHT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KFEIL', 'KING', 'FEIL', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AVIALL', 'ANGIE', 'VIALL', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SSARTORIS', 'SHON', 'SARTORIS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KCRNKOVICH', 'KALA', 'CRNKOVICH', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'YSANDLIN', 'YAJAIRA', 'SANDLIN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ACUCUTA', 'AMBROSE', 'CUCUTA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'RALKBSH', 'ROYAL', 'ALKBSH', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'BSLEEPER', 'BENITO', 'SLEEPER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KSELIGMANN', 'KRISTOFER', 'SELIGMANN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MHUGRON', 'MARGUERITE', 'HUGRON', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CBLAESE', 'CARMELINA', 'BLAESE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MAMPARO', 'MIREILLE', 'AMPARO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TWILCUTT', 'TOM', 'WILCUTT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KBRUNNETT', 'KEN', 'BRUNNETT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EDANDURAND', 'EUGENIE', 'DANDURAND', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DLEBLANC', 'DONNIE', 'LEBLANC', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CEBLING', 'CELENA', 'EBLING', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DABSON', 'DARREL', 'ABSON', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'VBLUEL', 'VINCENZO', 'BLUEL', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CKARLGAARD', 'CATHRINE', 'KARLGAARD', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CHUGUENIN', 'CHAUNCEY', 'HUGUENIN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EBLAIN', 'EMMITT', 'BLAIN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'RWLOCH', 'RHETT', 'WLOCH', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'PHARNISH', 'PAZ', 'HARNISH', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AAGIB', 'ALVINA', 'AGIB', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KKASICA', 'KAROLE', 'KASICA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ECURRANS', 'ERICK', 'CURRANS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DSTINNETTE', 'DEWEY', 'STINNETTE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DPROVINO', 'DANETTE', 'PROVINO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CMCCLENNY', 'CARLEEN', 'MCCLENNY', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SHASELHUHN', 'SHELLI', 'HASELHUHN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TLAMERE', 'TYSON', 'LAMERE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'BASWEGAN', 'BRANDEN', 'ASWEGAN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DSCHMITS', 'DEENA', 'SCHMITS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'BTEBAY', 'BEN', 'TEBAY', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'VWINTERBOTTOM', 'VAUGHN', 'WINTERBOTTOM', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'JSTRECZYWILK', 'JADWIGA', 'STRECZYWILK', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'GSIDNEY', 'GILDA', 'SIDNEY', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'LBARDO', 'LORIA', 'BARDO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CSEIRER', 'COLIN', 'SEIRER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CPALISCHAK', 'CESAR', 'PALISCHAK', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'HVEHRENKAMP', 'HOPE', 'VEHRENKAMP', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MSANDOUAL', 'MOHAMED', 'SANDOUAL', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'BCAGLE', 'BEE', 'CAGLE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TBORLING', 'TAD', 'BORLING', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'HWINDLAND', 'HELENE', 'WINDLAND', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'INEZ', 'IDELLA', 'NEZ', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TMAJERCIN', 'TRESSIE', 'MAJERCIN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CLEHNEN', 'CLAIRE', 'LEHNEN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CDELVA', 'CATALINA', 'DELVA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'SMAYHOOD', 'SHAUNNA', 'MAYHOOD', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MDAUBENMIRE', 'MYRIAM', 'DAUBENMIRE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EREES', 'ESSIE', 'REES', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'RBILDERBACK', 'ROSALEE', 'BILDERBACK', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AKATZENBERG', 'ANTOINE', 'KATZENBERG', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ABENZANGO', 'ANGELINA', 'BENZANGO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ESHIDER', 'EVONNE', 'SHIDER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'RLOSKOT', 'RODNEY', 'LOSKOT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'JDEIBERT', 'JACINTO', 'DEIBERT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'GCAFARELLI', 'GIDGET', 'CAFARELLI', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MSHILO', 'MARQUERITE', 'SHILO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TGLAY', 'THEO', 'GLAY', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'JSCHEIBELHUT', 'JEFFEREY', 'SCHEIBELHUT', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ANEMARD', 'ADOLFO', 'NEMARD', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CCALABRO', 'CALLIE', 'CALABRO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EMALM', 'EARNEST', 'MALM', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KTRUDELLE', 'KOREY', 'TRUDELLE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CSETTECASE', 'CAREY', 'SETTECASE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MBRITZ', 'MAURICIO', 'BRITZ', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ASKYERS', 'ALYSA', 'SKYERS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AGOUGHNOUR', 'ARMANDINA', 'GOUGHNOUR', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'JCECONI', 'JEROLD', 'CECONI', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DLANGEN', 'DELTA', 'LANGEN', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'CAHUJA', 'CARINA', 'AHUJA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'FMANNS', 'FOREST', 'MANNS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DTIELKING', 'DEANNA', 'TIELKING', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'MSMEDES', 'MINDY', 'SMEDES', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DFILIPPONE', 'DEBRAH', 'FILIPPONE', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EPHILIPPS', 'ELSA', 'PHILIPPS', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'KMONTEMURRO', 'KATHARINA', 'MONTEMURRO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'ASAULER', 'AI', 'SAULER', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'EZAMPEDRI', 'EVIA', 'ZAMPEDRI', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'AGRUDZINSKI', 'ANTON', 'GRUDZINSKI', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'IZIA', 'ISRAEL', 'ZIA', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'TIINO', 'TYESHA', 'IINO', now() );
insert into users ( user_name, first_name, last_name, user_add_date ) values ( 'DRAWI', 'DONETTA', 'RAWI', now() );

insert into clients_organizations ( client_id, org_id, start_date ) values ( 1, 1, now() );
insert into clients_organizations ( client_id, org_id, start_date ) values ( 2, 2, now() );
insert into clients_organizations ( client_id, org_id, start_date ) values ( 2, 3, now() );
insert into clients_organizations ( client_id, org_id, start_date ) values ( 2, 4, now() );

insert into organizations_users ( org_id, user_id, start_date ) values ( 1, 1, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 2, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 3, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 4, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 5, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 6, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 7, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 8, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 9, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 10, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 11, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 12, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 13, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 14, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 15, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 16, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 17, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 18, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 19, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 20, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 21, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 22, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 23, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 24, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 25, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 26, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 27, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 28, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 29, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 30, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 31, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 32, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 33, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 34, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 35, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 36, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 37, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 38, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 39, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 40, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 41, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 42, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 43, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 44, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 45, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 46, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 47, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 48, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 49, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 50, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 51, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 52, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 53, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 54, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 55, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 56, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 57, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 58, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 59, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 60, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 61, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 62, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 63, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 64, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 65, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 66, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 67, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 68, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 69, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 70, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 71, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 72, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 73, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 74, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 75, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 76, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 77, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 78, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 79, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 80, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 81, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 82, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 83, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 84, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 85, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 86, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 87, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 88, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 89, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 90, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 91, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 92, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 93, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 94, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 95, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 96, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 97, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 98, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 99, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 100, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 101, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 102, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 103, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 2, 104, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 3, 105, now() );
insert into organizations_users ( org_id, user_id, start_date ) values ( 4, 106, now() );

insert into users_roles (user_id, role_id, start_date) values (1,1,now());
insert into users_roles (user_id, role_id, start_date) values (2,3,now());
insert into users_roles (user_id, role_id, start_date) values (3,3,now());
insert into users_roles (user_id, role_id, start_date) values (4,3,now());
insert into users_roles (user_id, role_id, start_date) values (5,3,now());
insert into users_roles (user_id, role_id, start_date) values (6,3,now());
insert into users_roles (user_id, role_id, start_date) values (7,3,now());
insert into users_roles (user_id, role_id, start_date) values (8,3,now());
insert into users_roles (user_id, role_id, start_date) values (9,3,now());
insert into users_roles (user_id, role_id, start_date) values (10,3,now());
insert into users_roles (user_id, role_id, start_date) values (11,3,now());
insert into users_roles (user_id, role_id, start_date) values (12,3,now());
insert into users_roles (user_id, role_id, start_date) values (13,3,now());
insert into users_roles (user_id, role_id, start_date) values (14,3,now());
insert into users_roles (user_id, role_id, start_date) values (15,3,now());
insert into users_roles (user_id, role_id, start_date) values (16,3,now());
insert into users_roles (user_id, role_id, start_date) values (17,3,now());
insert into users_roles (user_id, role_id, start_date) values (18,3,now());
insert into users_roles (user_id, role_id, start_date) values (19,3,now());
insert into users_roles (user_id, role_id, start_date) values (20,3,now());
insert into users_roles (user_id, role_id, start_date) values (21,3,now());
insert into users_roles (user_id, role_id, start_date) values (22,3,now());
insert into users_roles (user_id, role_id, start_date) values (23,3,now());
insert into users_roles (user_id, role_id, start_date) values (24,3,now());
insert into users_roles (user_id, role_id, start_date) values (25,3,now());
insert into users_roles (user_id, role_id, start_date) values (26,3,now());
insert into users_roles (user_id, role_id, start_date) values (27,3,now());
insert into users_roles (user_id, role_id, start_date) values (28,3,now());
insert into users_roles (user_id, role_id, start_date) values (29,3,now());
insert into users_roles (user_id, role_id, start_date) values (30,3,now());
insert into users_roles (user_id, role_id, start_date) values (31,3,now());
insert into users_roles (user_id, role_id, start_date) values (32,3,now());
insert into users_roles (user_id, role_id, start_date) values (33,3,now());
insert into users_roles (user_id, role_id, start_date) values (34,3,now());
insert into users_roles (user_id, role_id, start_date) values (35,3,now());
insert into users_roles (user_id, role_id, start_date) values (36,3,now());
insert into users_roles (user_id, role_id, start_date) values (37,3,now());
insert into users_roles (user_id, role_id, start_date) values (38,3,now());
insert into users_roles (user_id, role_id, start_date) values (39,3,now());
insert into users_roles (user_id, role_id, start_date) values (40,3,now());
insert into users_roles (user_id, role_id, start_date) values (41,3,now());
insert into users_roles (user_id, role_id, start_date) values (42,3,now());
insert into users_roles (user_id, role_id, start_date) values (43,3,now());
insert into users_roles (user_id, role_id, start_date) values (44,3,now());
insert into users_roles (user_id, role_id, start_date) values (45,3,now());
insert into users_roles (user_id, role_id, start_date) values (46,3,now());
insert into users_roles (user_id, role_id, start_date) values (47,3,now());
insert into users_roles (user_id, role_id, start_date) values (48,3,now());
insert into users_roles (user_id, role_id, start_date) values (49,3,now());
insert into users_roles (user_id, role_id, start_date) values (50,3,now());
insert into users_roles (user_id, role_id, start_date) values (51,3,now());
insert into users_roles (user_id, role_id, start_date) values (52,3,now());
insert into users_roles (user_id, role_id, start_date) values (53,3,now());
insert into users_roles (user_id, role_id, start_date) values (54,3,now());
insert into users_roles (user_id, role_id, start_date) values (55,3,now());
insert into users_roles (user_id, role_id, start_date) values (56,3,now());
insert into users_roles (user_id, role_id, start_date) values (57,3,now());
insert into users_roles (user_id, role_id, start_date) values (58,3,now());
insert into users_roles (user_id, role_id, start_date) values (59,3,now());
insert into users_roles (user_id, role_id, start_date) values (60,3,now());
insert into users_roles (user_id, role_id, start_date) values (61,3,now());
insert into users_roles (user_id, role_id, start_date) values (62,3,now());
insert into users_roles (user_id, role_id, start_date) values (63,3,now());
insert into users_roles (user_id, role_id, start_date) values (64,3,now());
insert into users_roles (user_id, role_id, start_date) values (65,3,now());
insert into users_roles (user_id, role_id, start_date) values (66,3,now());
insert into users_roles (user_id, role_id, start_date) values (67,3,now());
insert into users_roles (user_id, role_id, start_date) values (68,3,now());
insert into users_roles (user_id, role_id, start_date) values (69,3,now());
insert into users_roles (user_id, role_id, start_date) values (70,3,now());
insert into users_roles (user_id, role_id, start_date) values (71,3,now());
insert into users_roles (user_id, role_id, start_date) values (72,3,now());
insert into users_roles (user_id, role_id, start_date) values (73,3,now());
insert into users_roles (user_id, role_id, start_date) values (74,3,now());
insert into users_roles (user_id, role_id, start_date) values (75,3,now());
insert into users_roles (user_id, role_id, start_date) values (76,3,now());
insert into users_roles (user_id, role_id, start_date) values (77,3,now());
insert into users_roles (user_id, role_id, start_date) values (78,3,now());
insert into users_roles (user_id, role_id, start_date) values (79,3,now());
insert into users_roles (user_id, role_id, start_date) values (80,3,now());
insert into users_roles (user_id, role_id, start_date) values (81,3,now());
insert into users_roles (user_id, role_id, start_date) values (82,3,now());
insert into users_roles (user_id, role_id, start_date) values (83,3,now());
insert into users_roles (user_id, role_id, start_date) values (84,3,now());
insert into users_roles (user_id, role_id, start_date) values (85,3,now());
insert into users_roles (user_id, role_id, start_date) values (86,3,now());
insert into users_roles (user_id, role_id, start_date) values (87,3,now());
insert into users_roles (user_id, role_id, start_date) values (88,3,now());
insert into users_roles (user_id, role_id, start_date) values (89,3,now());
insert into users_roles (user_id, role_id, start_date) values (90,3,now());
insert into users_roles (user_id, role_id, start_date) values (91,3,now());
insert into users_roles (user_id, role_id, start_date) values (92,3,now());
insert into users_roles (user_id, role_id, start_date) values (93,3,now());
insert into users_roles (user_id, role_id, start_date) values (94,3,now());
insert into users_roles (user_id, role_id, start_date) values (95,3,now());
insert into users_roles (user_id, role_id, start_date) values (96,3,now());
insert into users_roles (user_id, role_id, start_date) values (97,3,now());
insert into users_roles (user_id, role_id, start_date) values (98,3,now());
insert into users_roles (user_id, role_id, start_date) values (99,3,now());
insert into users_roles (user_id, role_id, start_date) values (100,3,now());
insert into users_roles (user_id, role_id, start_date) values (101,3,now());
insert into users_roles (user_id, role_id, start_date) values (102,3,now());
insert into users_roles (user_id, role_id, start_date) values (103,3,now());
insert into users_roles (user_id, role_id, start_date) values (104,3,now());
insert into users_roles (user_id, role_id, start_date) values (105,3,now());
insert into users_roles (user_id, role_id, start_date) values (106,3,now());
-----------------------------------------------
insert into role_groups(role_group_id, role_group_name, role_group_add_date) values (1,'group_id',now());
-----------------------------------------------
insert into role_groups_roles( role_group_id, role_id, start_date) values (1,1,now());
-----------------------------------------------


-- select * from organizations;

-- SELECT row_to_json(o) FROM organizations as o;

-- SELECT ROW_TO_JSON(c) FROM clients as c where c.client_id=1

-- SELECT ROW_TO_JSON(o) FROM organizations as o where o.org_id=1

-- select o.* from clients_organizations co, organizations o where co.org_id = o.org_id and co.client_id = 1;

/*select ROW_TO_JSON(v) from (
                  select u.*, ou.start_date, ou.end_date
                  from organizations_users ou,
                       users u
                  where ou.user_id = u.user_id and ou.end_date is null
                    and ou.org_id = 1
) v;*/

-- insert into users_roles (user_id, role_id, start_date) values (1,3,now());

commit;
