apiVersion: v1
kind: Service

metadata:
  name: postgres-server

spec:
  ports:
    - name: postgres-30432
      port: 5432
      nodePort: 30432
  selector:
    app: postgres-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-server

spec:
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
        - image: timescale/timescaledb:2.1.0-pg11-oss
          name: postgres
          env:
            - name: TZ
              value: "Australia/Sydney"
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          command:
            - "docker-entrypoint.sh"
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "timescaledb.telemetry_level=off"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 1
            periodSeconds: 1
      volumes:
        - name: postgresql-conf
          configMap:
            name: postgresql-config